; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes='simplifycfg<hoist-common-insts>' -simplifycfg-require-and-preserve-domtree=1 -S < %s | FileCheck %s

declare void @llvm.assume(i1)
declare i1 @cond()
declare void @f()
declare void @g()

; An assume and its condition in only one successor do not prevent hoisting
; the common call; they are skipped and stay behind.
define void @skip_one_sided_assume(i32 %x) {
; CHECK-LABEL: define void @skip_one_sided_assume(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp eq i32 [[X]], 0
; CHECK-NEXT:    [[T0:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C0]], label %[[IF0:.*]], label %[[ELSE:.*]]
; CHECK:       [[IF0]]:
; CHECK-NEXT:    br i1 [[T0]], label %[[CALLF:.*]], label %[[EXIT:.*]]
; CHECK:       [[CALLF]]:
; CHECK-NEXT:    call void @f()
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    [[C1:%.*]] = icmp eq i32 [[X]], 1
; CHECK-NEXT:    call void @llvm.assume(i1 [[C1]])
; CHECK-NEXT:    br i1 [[T0]], label %[[CALLG:.*]], label %[[EXIT]]
; CHECK:       [[CALLG]]:
; CHECK-NEXT:    call void @g()
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp eq i32 %x, 0
  br i1 %c0, label %if0, label %else

if0:
  %t0 = call i1 @cond()
  br i1 %t0, label %callf, label %exit

callf:
  call void @f()
  br label %exit

else:
  %c1 = icmp eq i32 %x, 1
  call void @llvm.assume(i1 %c1)
  %t1 = call i1 @cond()
  br i1 %t1, label %callg, label %exit

callg:
  call void @g()
  br label %exit

exit:
  ret void
}

; A multi-level condition computation feeding an assume (add -> icmp ->
; assume) is skipped as a whole; the common call is still hoisted.
define void @skip_assume_feeder_chain(i32 %x) {
; CHECK-LABEL: define void @skip_assume_feeder_chain(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp eq i32 [[X]], 0
; CHECK-NEXT:    [[T0:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C0]], label %[[IF0:.*]], label %[[ELSE:.*]]
; CHECK:       [[IF0]]:
; CHECK-NEXT:    br i1 [[T0]], label %[[CALLF:.*]], label %[[EXIT:.*]]
; CHECK:       [[CALLF]]:
; CHECK-NEXT:    call void @f()
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    [[A:%.*]] = add nuw i32 [[X]], 1
; CHECK-NEXT:    [[C1:%.*]] = icmp ult i32 [[A]], 10
; CHECK-NEXT:    call void @llvm.assume(i1 [[C1]])
; CHECK-NEXT:    br i1 [[T0]], label %[[CALLG:.*]], label %[[EXIT]]
; CHECK:       [[CALLG]]:
; CHECK-NEXT:    call void @g()
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp eq i32 %x, 0
  br i1 %c0, label %if0, label %else

if0:
  %t0 = call i1 @cond()
  br i1 %t0, label %callf, label %exit

callf:
  call void @f()
  br label %exit

else:
  %a = add nuw i32 %x, 1
  %c1 = icmp ult i32 %a, 10
  call void @llvm.assume(i1 %c1)
  %t1 = call i1 @cond()
  br i1 %t1, label %callg, label %exit

callg:
  call void @g()
  br label %exit

exit:
  ret void
}

; Identical assumes in both successors are hoisted and merged, not skipped.
define void @merge_identical_assumes(i1 %c, i32 %x) {
; CHECK-LABEL: define void @merge_identical_assumes(
; CHECK-SAME: i1 [[C:%.*]], i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[V1:%.*]] = icmp ult i32 [[X]], 10
; CHECK-NEXT:    call void @llvm.assume(i1 [[V1]])
; CHECK-NEXT:    br i1 [[C]], label %[[A:.*]], label %[[B:.*]]
; CHECK:       [[COMMON_RET:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[A]]:
; CHECK-NEXT:    call void @f()
; CHECK-NEXT:    br label %[[COMMON_RET]]
; CHECK:       [[B]]:
; CHECK-NEXT:    call void @g()
; CHECK-NEXT:    br label %[[COMMON_RET]]
;
entry:
  br i1 %c, label %a, label %b

a:
  %v1 = icmp ult i32 %x, 10
  call void @llvm.assume(i1 %v1)
  call void @f()
  ret void

b:
  %v2 = icmp ult i32 %x, 10
  call void @llvm.assume(i1 %v2)
  call void @g()
  ret void
}

; Negative test: the store must not be hoisted above the load feeding the
; assume; doing so would make the load observe the stored value and turn a
; defined execution into assume(false).
define void @no_hoist_store_above_skipped_load(i1 %c, ptr %p) {
; CHECK-LABEL: define void @no_hoist_store_above_skipped_load(
; CHECK-SAME: i1 [[C:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C]], label %[[A:.*]], label %[[B:.*]]
; CHECK:       [[COMMON_RET:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[A]]:
; CHECK-NEXT:    [[V:%.*]] = load i1, ptr [[P]], align 1
; CHECK-NEXT:    call void @llvm.assume(i1 [[V]])
; CHECK-NEXT:    store i1 false, ptr [[P]], align 1
; CHECK-NEXT:    call void @f()
; CHECK-NEXT:    br label %[[COMMON_RET]]
; CHECK:       [[B]]:
; CHECK-NEXT:    store i1 false, ptr [[P]], align 1
; CHECK-NEXT:    call void @g()
; CHECK-NEXT:    br label %[[COMMON_RET]]
;
entry:
  br i1 %c, label %a, label %b

a:
  %v = load i1, ptr %p
  call void @llvm.assume(i1 %v)
  store i1 false, ptr %p
  call void @f()
  ret void

b:
  store i1 false, ptr %p
  call void @g()
  ret void
}

; Negative test: skipped assumes stay behind, so the branch must not be
; folded away (that would silently drop the assume).
define void @no_terminator_fold_with_skipped_assume(i1 %c, ptr %p) {
; CHECK-LABEL: define void @no_terminator_fold_with_skipped_assume(
; CHECK-SAME: i1 [[C:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C]], label %[[A:.*]], label %[[EXIT:.*]]
; CHECK:       [[A]]:
; CHECK-NEXT:    [[V:%.*]] = load i1, ptr [[P]], align 1
; CHECK-NEXT:    call void @llvm.assume(i1 [[V]])
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br i1 %c, label %a, label %b

a:
  %v = load i1, ptr %p
  call void @llvm.assume(i1 %v)
  br label %exit

b:
  br label %exit

exit:
  ret void
}

; Negative test: assumes with operand bundles are point facts and are not
; skipped.
define void @no_skip_operand_bundles(i1 %c, ptr %p) {
; CHECK-LABEL: define void @no_skip_operand_bundles(
; CHECK-SAME: i1 [[C:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C]], label %[[A:.*]], label %[[B:.*]]
; CHECK:       [[COMMON_RET:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[A]]:
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[P]], i64 16) ]
; CHECK-NEXT:    [[T0:%.*]] = call i1 @cond()
; CHECK-NEXT:    call void @f()
; CHECK-NEXT:    br label %[[COMMON_RET]]
; CHECK:       [[B]]:
; CHECK-NEXT:    [[T1:%.*]] = call i1 @cond()
; CHECK-NEXT:    call void @g()
; CHECK-NEXT:    br label %[[COMMON_RET]]
;
entry:
  br i1 %c, label %a, label %b

a:
  call void @llvm.assume(i1 true) ["align"(ptr %p, i64 16)]
  %t0 = call i1 @cond()
  call void @f()
  ret void

b:
  %t1 = call i1 @cond()
  call void @g()
  ret void
}

; Negative test: a musttail call must not be hoisted when an assume was
; skipped; its ret cannot follow it into the predecessor because the
; skipped assume stays behind.
declare void @callee(i1, i32)
define void @no_hoist_musttail_with_skipped_assume(i1 %c, i32 %x) {
; CHECK-LABEL: define void @no_hoist_musttail_with_skipped_assume(
; CHECK-SAME: i1 [[C:%.*]], i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[C]], label %[[A:.*]], label %[[B:.*]]
; CHECK:       [[A]]:
; CHECK-NEXT:    [[C1:%.*]] = icmp eq i32 [[X]], 1
; CHECK-NEXT:    call void @llvm.assume(i1 [[C1]])
; CHECK-NEXT:    musttail call void @callee(i1 [[C]], i32 [[X]])
; CHECK-NEXT:    ret void
; CHECK:       [[B]]:
; CHECK-NEXT:    musttail call void @callee(i1 [[C]], i32 [[X]])
; CHECK-NEXT:    ret void
;
entry:
  br i1 %c, label %a, label %b

a:
  %c1 = icmp eq i32 %x, 1
  call void @llvm.assume(i1 %c1)
  musttail call void @callee(i1 %c, i32 %x)
  ret void

b:
  musttail call void @callee(i1 %c, i32 %x)
  ret void
}
