; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=simplifycfg -simplifycfg-require-and-preserve-domtree=1 -S < %s | FileCheck %s

declare i1 @cond()
declare void @f()
declare void @g()
declare void @llvm.assume(i1)

; An assume over the branched-on argument in a successor is hoisted into the
; entry block, weakened with the branch condition.
define void @hoist_assume_from_false_succ(i32 %x) {
;
; CHECK-LABEL: define void @hoist_assume_from_false_succ(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp eq i32 [[X]], 0
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ult i32 [[X]], 2
; CHECK-NEXT:    call void @llvm.assume(i1 [[TMP0]])
; CHECK-NEXT:    br i1 [[C0]], label %[[IF0:.*]], label %[[ELSE:.*]]
; CHECK:       [[IF0]]:
; CHECK-NEXT:    [[T0:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[T0]], label %[[CALLF:.*]], label %[[EXIT:.*]]
; CHECK:       [[CALLF]]:
; CHECK-NEXT:    call void @f()
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    [[T1:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[T1]], label %[[CALLG:.*]], label %[[EXIT]]
; CHECK:       [[CALLG]]:
; CHECK-NEXT:    call void @g()
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp eq i32 %x, 0
  br i1 %c0, label %if0, label %else

if0:
  %t0 = call i1 @cond()
  br i1 %t0, label %callf, label %exit

callf:
  call void @f()
  br label %exit

else:
  %c1 = icmp eq i32 %x, 1
  call void @llvm.assume(i1 %c1)
  %t1 = call i1 @cond()
  br i1 %t1, label %callg, label %exit

callg:
  call void @g()
  br label %exit

exit:
  ret void
}

; Same, with the assume in the true successor; the guard is negated.
define void @hoist_assume_from_true_succ(i32 %x) {
;
; CHECK-LABEL: define void @hoist_assume_from_true_succ(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp ne i32 [[X]], 0
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ult i32 [[X]], 8
; CHECK-NEXT:    call void @llvm.assume(i1 [[TMP0]])
; CHECK-NEXT:    br i1 [[C0]], label %[[THEN:.*]], label %[[EXIT:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    call void @f()
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp ne i32 %x, 0
  br i1 %c0, label %then, label %exit

then:
  %c1 = icmp ult i32 %x, 8
  call void @llvm.assume(i1 %c1)
  call void @f()
  br label %exit

exit:
  ret void
}

; Negative test: the branch condition is unrelated to the assumed argument,
; so the assume is not hoisted (block speculation handles this instead).
define i32 @no_hoist_unrelated_branch(i1 %c, i32 %x) {
;
; CHECK-LABEL: define i32 @no_hoist_unrelated_branch(
; CHECK-SAME: i1 [[C:%.*]], i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[SPEC_SELECT:%.*]] = select i1 [[C]], i32 1, i32 0
; CHECK-NEXT:    ret i32 [[SPEC_SELECT]]
;
entry:
  br i1 %c, label %if, label %join

if:
  %cmp = icmp ne i32 %x, 0
  call void @llvm.assume(i1 %cmp)
  br label %join

join:
  %phi = phi i32 [ 0, %entry ], [ 1, %if ]
  ret i32 %phi
}

; Negative test: a non-guaranteed-to-transfer instruction precedes the assume.
define void @no_hoist_not_guaranteed_to_execute(i32 %x) {
;
; CHECK-LABEL: define void @no_hoist_not_guaranteed_to_execute(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp eq i32 [[X]], 0
; CHECK-NEXT:    br i1 [[C0]], label %[[IF0:.*]], label %[[ELSE:.*]]
; CHECK:       [[IF0]]:
; CHECK-NEXT:    call void @f()
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    [[T:%.*]] = call i1 @cond()
; CHECK-NEXT:    [[C1:%.*]] = icmp eq i32 [[X]], 1
; CHECK-NEXT:    call void @llvm.assume(i1 [[C1]])
; CHECK-NEXT:    call void @g()
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp eq i32 %x, 0
  br i1 %c0, label %if0, label %else

if0:
  call void @f()
  br label %exit

else:
  %t = call i1 @cond()
  %c1 = icmp eq i32 %x, 1
  call void @llvm.assume(i1 %c1)
  call void @g()
  br label %exit

exit:
  ret void
}

; The union {0} u {5} has no single equivalent icmp; the assume is left alone.
define void @no_hoist_union_not_representable(i32 %x) {
; CHECK-LABEL: define void @no_hoist_union_not_representable(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp eq i32 [[X]], 0
; CHECK-NEXT:    br i1 [[C0]], label %[[IF0:.*]], label %[[ELSE:.*]]
; CHECK:       [[IF0]]:
; CHECK-NEXT:    call void @f()
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    [[C1:%.*]] = icmp eq i32 [[X]], 5
; CHECK-NEXT:    call void @llvm.assume(i1 [[C1]])
; CHECK-NEXT:    call void @g()
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp eq i32 %x, 0
  br i1 %c0, label %if0, label %else

if0:
  call void @f()
  br label %exit

else:
  %c1 = icmp eq i32 %x, 5
  call void @llvm.assume(i1 %c1)
  call void @g()
  br label %exit

exit:
  ret void
}

; Assumes in both successors are hoisted, with the guard negated per edge.
define void @hoist_from_both_succs(i32 %x) {
; CHECK-LABEL: define void @hoist_from_both_succs(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp slt i32 [[X]], 0
; CHECK-NEXT:    [[TMP0:%.*]] = icmp sge i32 [[X]], -7
; CHECK-NEXT:    call void @llvm.assume(i1 [[TMP0]])
; CHECK-NEXT:    [[TMP1:%.*]] = icmp slt i32 [[X]], 8
; CHECK-NEXT:    call void @llvm.assume(i1 [[TMP1]])
; CHECK-NEXT:    br i1 [[C0]], label %[[NEG:.*]], label %[[POS:.*]]
; CHECK:       [[NEG]]:
; CHECK-NEXT:    call void @f()
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[POS]]:
; CHECK-NEXT:    call void @g()
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp slt i32 %x, 0
  br i1 %c0, label %neg, label %pos

neg:
  %c1 = icmp sgt i32 %x, -8
  call void @llvm.assume(i1 %c1)
  call void @f()
  br label %exit

pos:
  %c2 = icmp slt i32 %x, 8
  call void @llvm.assume(i1 %c2)
  call void @g()
  br label %exit

exit:
  ret void
}

; A swapped icmp with the constant on the LHS is handled.
define void @hoist_swapped_icmp(i32 %x) {
; CHECK-LABEL: define void @hoist_swapped_icmp(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp eq i32 [[X]], 0
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ult i32 [[X]], 2
; CHECK-NEXT:    call void @llvm.assume(i1 [[TMP0]])
; CHECK-NEXT:    br i1 [[C0]], label %[[IF0:.*]], label %[[ELSE:.*]]
; CHECK:       [[IF0]]:
; CHECK-NEXT:    call void @f()
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    call void @g()
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp eq i32 %x, 0
  br i1 %c0, label %if0, label %else

if0:
  call void @f()
  br label %exit

else:
  %c1 = icmp ugt i32 2, %x
  call void @llvm.assume(i1 %c1)
  call void @g()
  br label %exit

exit:
  ret void
}

; Negative test: assumes with operand bundles are point facts and stay put
; (the verifier requires their condition to be i1 true, so they can never
; match an argument icmp anyway).
define void @no_hoist_operand_bundles(i32 %x, ptr %p) {
; CHECK-LABEL: define void @no_hoist_operand_bundles(
; CHECK-SAME: i32 [[X:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp eq i32 [[X]], 0
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ult i32 [[X]], 2
; CHECK-NEXT:    call void @llvm.assume(i1 [[TMP0]])
; CHECK-NEXT:    br i1 [[C0]], label %[[IF0:.*]], label %[[ELSE:.*]]
; CHECK:       [[IF0]]:
; CHECK-NEXT:    call void @f()
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[P]], i64 16) ]
; CHECK-NEXT:    call void @g()
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp eq i32 %x, 0
  br i1 %c0, label %if0, label %else

if0:
  call void @f()
  br label %exit

else:
  call void @llvm.assume(i1 true) ["align"(ptr %p, i64 16)]
  %c1 = icmp eq i32 %x, 1
  call void @llvm.assume(i1 %c1)
  call void @g()
  br label %exit

exit:
  ret void
}

; Negative test: the successor has a second predecessor, so the assume is
; not guaranteed to be reached only through the guarded edge; removing it
; there would be wrong for the other path.
define void @no_hoist_multiple_preds(i32 %x, i1 %p) {
; CHECK-LABEL: define void @no_hoist_multiple_preds(
; CHECK-SAME: i32 [[X:%.*]], i1 [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp eq i32 [[X]], 0
; CHECK-NEXT:    br i1 [[C0]], label %[[IF0:.*]], label %[[ELSE:.*]]
; CHECK:       [[IF0]]:
; CHECK-NEXT:    call void @f()
; CHECK-NEXT:    br i1 [[P]], label %[[ELSE]], label %[[EXIT:.*]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    [[C1:%.*]] = icmp eq i32 [[X]], 1
; CHECK-NEXT:    call void @llvm.assume(i1 [[C1]])
; CHECK-NEXT:    call void @g()
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp eq i32 %x, 0
  br i1 %c0, label %if0, label %else

if0:
  call void @f()
  br i1 %p, label %else, label %exit

else:
  %c1 = icmp eq i32 %x, 1
  call void @llvm.assume(i1 %c1)
  call void @g()
  br label %exit

exit:
  ret void
}

; An assume already implied by the edge condition adds no information and is
; simply deleted.
define void @delete_implied_assume(i32 %x) {
; CHECK-LABEL: define void @delete_implied_assume(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp eq i32 [[X]], 0
; CHECK-NEXT:    br i1 [[C0]], label %[[IF0:.*]], label %[[ELSE:.*]]
; CHECK:       [[IF0]]:
; CHECK-NEXT:    call void @f()
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    call void @g()
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp eq i32 %x, 0
  br i1 %c0, label %if0, label %else

if0:
  %c1 = icmp ult i32 %x, 8
  call void @llvm.assume(i1 %c1)
  call void @f()
  br label %exit

else:
  call void @g()
  br label %exit

exit:
  ret void
}
