; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=aarch64 < %s | FileCheck %s

; The unsigned range makes the mask redundant.
define i32 @and_low_bit(i32 range(i32 0, 2) %x) {
; CHECK-LABEL: and_low_bit:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ret
  %r = and i32 %x, 1
  ret i32 %r
}

define i64 @no_mask_needed(i64 range(i64 0, 100) %x) {
; CHECK-LABEL: no_mask_needed:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ret
  %r = and i64 %x, 127
  ret i64 %r
}

; The signed range makes the sign extension redundant.
define i32 @sext_inreg(i32 range(i32 -8, 8) %x) {
; CHECK-LABEL: sext_inreg:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ret
  %t = trunc i32 %x to i8
  %e = sext i8 %t to i32
  ret i32 %e
}

; Known zero bits from the range fold the shift result to zero.
define i32 @known_zero_shift(i32 range(i32 0, 2) %x) {
; CHECK-LABEL: known_zero_shift:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov w0, wzr
; CHECK-NEXT:    ret
  %r = lshr i32 %x, 1
  ret i32 %r
}

; Negative test: the range does not restrict the low bits.
define i32 @range_does_not_help(i32 range(i32 0, 1000) %x) {
; CHECK-LABEL: range_does_not_help:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and w0, w0, #0x7f
; CHECK-NEXT:    ret
  %r = and i32 %x, 127
  ret i32 %r
}

; The range stacks with the zeroext ABI attribute (both asserts are emitted
; and stripped for the argument fast path).
define i32 @zeroext_and_range(i8 zeroext range(i8 0, 2) %x) {
; CHECK-LABEL: zeroext_and_range:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ret
  %e = zext i8 %x to i32
  %r = and i32 %e, 1
  ret i32 %r
}

; The range stacks with the signext ABI attribute.
define i32 @signext_and_range(i8 signext range(i8 -8, 8) %x) {
; CHECK-LABEL: signext_and_range:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ret
  %e = sext i8 %x to i32
  %t = trunc i32 %e to i4
  %s = sext i4 %t to i32
  ret i32 %s
}

; A range on a call result now uses the signed form as well.
declare range(i32 -8, 8) i32 @ext()
define i32 @call_result_signed_range() {
; CHECK-LABEL: call_result_signed_range:
; CHECK:       // %bb.0:
; CHECK-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset w30, -16
; CHECK-NEXT:    bl ext
; CHECK-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
  %v = call i32 @ext()
  %t = trunc i32 %v to i8
  %e = sext i8 %t to i32
  ret i32 %e
}

; A wrapped range {-1, 0} still proves a one-bit sign extension.
define i32 @wrapped_range_sext(i32 range(i32 -1, 1) %x) {
; CHECK-LABEL: wrapped_range_sext:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ret
  %t = trunc i32 %x to i1
  %e = sext i1 %t to i32
  ret i32 %e
}
