; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=function-attrs -S < %s | FileCheck %s

declare void @llvm.assume(i1)
declare void @unknown()
declare i1 @cond() willreturn nounwind

; A guaranteed-to-execute entry-block assume constrains the argument.
define void @simple(i32 %x) {
; CHECK-LABEL: define void @simple(
; CHECK-SAME: i32 range(i32 0, 2) [[X:%.*]]) #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C:%.*]] = icmp ult i32 [[X]], 2
; CHECK-NEXT:    call void @llvm.assume(i1 [[C]])
; CHECK-NEXT:    ret void
;
entry:
  %c = icmp ult i32 %x, 2
  call void @llvm.assume(i1 %c)
  ret void
}

; Disjunctions of icmps over the same argument are unioned.
define void @or_condition(i32 %x) {
; CHECK-LABEL: define void @or_condition(
; CHECK-SAME: i32 range(i32 0, 11) [[X:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp eq i32 [[X]], 0
; CHECK-NEXT:    [[C1:%.*]] = icmp eq i32 [[X]], 10
; CHECK-NEXT:    [[OR:%.*]] = or i1 [[C0]], [[C1]]
; CHECK-NEXT:    call void @llvm.assume(i1 [[OR]])
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp eq i32 %x, 0
  %c1 = icmp eq i32 %x, 10
  %or = or i1 %c0, %c1
  call void @llvm.assume(i1 %or)
  ret void
}

; Conjunctions contribute independent facts (also for multiple arguments).
define void @and_condition(i32 %x, i64 %y) {
; CHECK-LABEL: define void @and_condition(
; CHECK-SAME: i32 range(i32 6, 0) [[X:%.*]], i64 range(i64 -9223372036854775808, 100) [[Y:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp ugt i32 [[X]], 5
; CHECK-NEXT:    [[C1:%.*]] = icmp slt i64 [[Y]], 100
; CHECK-NEXT:    [[AND:%.*]] = and i1 [[C0]], [[C1]]
; CHECK-NEXT:    call void @llvm.assume(i1 [[AND]])
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp ugt i32 %x, 5
  %c1 = icmp slt i64 %y, 100
  %and = and i1 %c0, %c1
  call void @llvm.assume(i1 %and)
  ret void
}

; Multiple assumes intersect.
define void @two_assumes(i32 %x) {
; CHECK-LABEL: define void @two_assumes(
; CHECK-SAME: i32 range(i32 11, 100) [[X:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp ult i32 [[X]], 100
; CHECK-NEXT:    call void @llvm.assume(i1 [[C0]])
; CHECK-NEXT:    [[C1:%.*]] = icmp ugt i32 [[X]], 10
; CHECK-NEXT:    call void @llvm.assume(i1 [[C1]])
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp ult i32 %x, 100
  call void @llvm.assume(i1 %c0)
  %c1 = icmp ugt i32 %x, 10
  call void @llvm.assume(i1 %c1)
  ret void
}

; An assume of a nonzero value becomes a wrapped range.
define void @nonzero(i64 %n) {
; CHECK-LABEL: define void @nonzero(
; CHECK-SAME: i64 range(i64 1, 0) [[N:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C:%.*]] = icmp ne i64 [[N]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[C]])
; CHECK-NEXT:    ret void
;
entry:
  %c = icmp ne i64 %n, 0
  call void @llvm.assume(i1 %c)
  ret void
}

; Negative test: a call that may not return precedes the assume, so the
; fact is not guaranteed to hold on every execution.
define void @not_guaranteed_to_execute(i32 %x) {
; CHECK-LABEL: define void @not_guaranteed_to_execute(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @unknown()
; CHECK-NEXT:    [[C:%.*]] = icmp ult i32 [[X]], 2
; CHECK-NEXT:    call void @llvm.assume(i1 [[C]])
; CHECK-NEXT:    ret void
;
entry:
  call void @unknown()
  %c = icmp ult i32 %x, 2
  call void @llvm.assume(i1 %c)
  ret void
}

; A willreturn nounwind call before the assume is fine.
define void @guaranteed_past_call(i32 %x) {
; CHECK-LABEL: define void @guaranteed_past_call(
; CHECK-SAME: i32 range(i32 0, 2) [[X:%.*]]) #[[ATTR3:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[T:%.*]] = call i1 @cond()
; CHECK-NEXT:    [[C:%.*]] = icmp ult i32 [[X]], 2
; CHECK-NEXT:    call void @llvm.assume(i1 [[C]])
; CHECK-NEXT:    ret void
;
entry:
  %t = call i1 @cond()
  %c = icmp ult i32 %x, 2
  call void @llvm.assume(i1 %c)
  ret void
}

; Negative test: assume not in the entry block.
define void @not_in_entry(i32 %x, i1 %p) {
; CHECK-LABEL: define void @not_in_entry(
; CHECK-SAME: i32 [[X:%.*]], i1 [[P:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[P]], label %[[THEN:.*]], label %[[EXIT:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[C:%.*]] = icmp ult i32 [[X]], 2
; CHECK-NEXT:    call void @llvm.assume(i1 [[C]])
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br i1 %p, label %then, label %exit

then:
  %c = icmp ult i32 %x, 2
  call void @llvm.assume(i1 %c)
  br label %exit

exit:
  ret void
}

; Negative test: condition is not an icmp against a constant.
define void @not_constant(i32 %x, i32 %y) {
; CHECK-LABEL: define void @not_constant(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C:%.*]] = icmp ult i32 [[X]], [[Y]]
; CHECK-NEXT:    call void @llvm.assume(i1 [[C]])
; CHECK-NEXT:    ret void
;
entry:
  %c = icmp ult i32 %x, %y
  call void @llvm.assume(i1 %c)
  ret void
}

; An existing range attribute is intersected.
define void @intersect_existing(i32 range(i32 0, 10) %x) {
; CHECK-LABEL: define void @intersect_existing(
; CHECK-SAME: i32 range(i32 5, 10) [[X:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C:%.*]] = icmp ugt i32 [[X]], 4
; CHECK-NEXT:    call void @llvm.assume(i1 [[C]])
; CHECK-NEXT:    ret void
;
entry:
  %c = icmp ugt i32 %x, 4
  call void @llvm.assume(i1 %c)
  ret void
}

; A swapped icmp with the constant on the LHS is handled.
define void @swapped_icmp(i32 %x) {
; CHECK-LABEL: define void @swapped_icmp(
; CHECK-SAME: i32 range(i32 0, 2) [[X:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C:%.*]] = icmp ugt i32 2, [[X]]
; CHECK-NEXT:    call void @llvm.assume(i1 [[C]])
; CHECK-NEXT:    ret void
;
entry:
  %c = icmp ugt i32 2, %x
  call void @llvm.assume(i1 %c)
  ret void
}

; A conjunction of disjunctions contributes each disjunctive fact.
define void @and_of_ors(i32 %x, i32 %y) {
; CHECK-LABEL: define void @and_of_ors(
; CHECK-SAME: i32 range(i32 0, 2) [[X:%.*]], i32 range(i32 8, 10) [[Y:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[X0:%.*]] = icmp eq i32 [[X]], 0
; CHECK-NEXT:    [[X1:%.*]] = icmp eq i32 [[X]], 1
; CHECK-NEXT:    [[XOR:%.*]] = or i1 [[X0]], [[X1]]
; CHECK-NEXT:    [[Y0:%.*]] = icmp eq i32 [[Y]], 8
; CHECK-NEXT:    [[Y1:%.*]] = icmp eq i32 [[Y]], 9
; CHECK-NEXT:    [[YOR:%.*]] = or i1 [[Y0]], [[Y1]]
; CHECK-NEXT:    [[AND:%.*]] = and i1 [[XOR]], [[YOR]]
; CHECK-NEXT:    call void @llvm.assume(i1 [[AND]])
; CHECK-NEXT:    ret void
;
entry:
  %x0 = icmp eq i32 %x, 0
  %x1 = icmp eq i32 %x, 1
  %xor = or i1 %x0, %x1
  %y0 = icmp eq i32 %y, 8
  %y1 = icmp eq i32 %y, 9
  %yor = or i1 %y0, %y1
  %and = and i1 %xor, %yor
  call void @llvm.assume(i1 %and)
  ret void
}

; Negative test: a disjunction over two different arguments constrains
; neither of them.
define void @or_of_two_args(i32 %x, i32 %y) {
; CHECK-LABEL: define void @or_of_two_args(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C0:%.*]] = icmp ult i32 [[X]], 2
; CHECK-NEXT:    [[C1:%.*]] = icmp ult i32 [[Y]], 2
; CHECK-NEXT:    [[OR:%.*]] = or i1 [[C0]], [[C1]]
; CHECK-NEXT:    call void @llvm.assume(i1 [[OR]])
; CHECK-NEXT:    ret void
;
entry:
  %c0 = icmp ult i32 %x, 2
  %c1 = icmp ult i32 %y, 2
  %or = or i1 %c0, %c1
  call void @llvm.assume(i1 %or)
  ret void
}

; Negative test: assumes with operand bundles are ignored, but do not stop
; the scan.
define void @operand_bundles(i32 %x, ptr %p) {
; CHECK-LABEL: define void @operand_bundles(
; CHECK-SAME: i32 range(i32 0, 2) [[X:%.*]], ptr nofree readnone captures(none) [[P:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[P]], i64 16) ]
; CHECK-NEXT:    [[C:%.*]] = icmp ult i32 [[X]], 2
; CHECK-NEXT:    call void @llvm.assume(i1 [[C]])
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.assume(i1 true) ["align"(ptr %p, i64 16)]
  %c = icmp ult i32 %x, 2
  call void @llvm.assume(i1 %c)
  ret void
}
