; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes='default<O2>' -S < %s | FileCheck %s

; End-to-end test for turning branch-guarded argument assumes into range
; parameter attributes: SimplifyCFG hoists the assume into the entry block
; weakened with the branch condition, FunctionAttrs promotes it to a range
; attribute, and InstCombine then deletes the redundant assume and folds
; the mask away using the attribute.

declare void @g()

define i32 @guarded_assume_to_range_attr(i32 %x) {
; CHECK-LABEL: define range(i32 0, 8) i32 @guarded_assume_to_range_attr(
; CHECK-SAME: i32 returned range(i32 0, 8) [[X:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @g()
; CHECK-NEXT:    ret i32 [[X]]
;
entry:
  %c0 = icmp eq i32 %x, 0
  br i1 %c0, label %if, label %else

if:
  call void @g()
  br label %exit

else:
  %c1 = icmp ult i32 %x, 8
  call void @llvm.assume(i1 %c1)
  call void @g()
  br label %exit

exit:
  %r = and i32 %x, 15
  ret i32 %r
}
